codecov:
  token: e71cac93-7a3a-43e1-87cc-e04024210737
  branch: master
  bot: null
  
coverage:
  precision: 2
  round: down
  range: "70...100"

notify:
  gitter:
    _custom_:
      url: https://gitter.im/channingwalton/typeclassopedia
      threshold: null
      branches: null
      message: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default
